/**
 * tailwind.config.js
 * Tailwind CSS design-token configuration for the portfolio.
 * Separated from index.html for maintainability.
 */
tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "primary":                    "#adc6ff",
                "on-background":              "#e0e2ed",
                "surface-dim":                "#10131b",
                "secondary-fixed":            "#bee9ff",
                "secondary-fixed-dim":        "#68d3ff",
                "tertiary-fixed":             "#ffdbcc",
                "inverse-primary":            "#005bc1",
                "inverse-on-surface":         "#2d3039",
                "secondary":                  "#68d3ff",
                "on-surface":                 "#e0e2ed",
                "surface-container-lowest":   "#0b0e16",
                "tertiary-fixed-dim":         "#ffb595",
                "on-tertiary-fixed-variant":  "#7c2e00",
                "error":                      "#ffb4ab",
                "surface":                    "#10131b",
                "secondary-container":        "#139cc7",
                "error-container":            "#93000a",
                "tertiary-container":         "#ef6719",
                "surface-container-high":     "#272a32",
                "on-surface-variant":         "#c1c6d7",
                "on-tertiary-fixed":          "#351000",
                "on-secondary-fixed-variant": "#004d64",
                "on-primary":                 "#002e69",
                "on-tertiary-container":      "#4c1a00",
                "primary-fixed-dim":          "#adc6ff",
                "on-error":                   "#690005",
                "outline":                    "#8b90a0",
                "tertiary":                   "#ffb595",
                "surface-bright":             "#363942",
                "on-tertiary":                "#571e00",
                "inverse-surface":            "#e0e2ed",
                "on-secondary-container":     "#002e3d",
                "surface-container":          "#1c2028",
                "outline-variant":            "#414755",
                "surface-container-low":      "#181c23",
                "primary-fixed":              "#d8e2ff",
                "on-error-container":         "#ffdad6",
                "on-secondary-fixed":         "#001f2a",
                "on-primary-fixed-variant":   "#004493",
                "surface-tint":               "#adc6ff",
                "on-primary-fixed":           "#001a41",
                "on-primary-container":       "#00285c",
                "surface-container-highest":  "#31353d",
                "background":                 "#10131b",
                "surface-variant":            "#31353d",
                "on-secondary":               "#003546",
                "primary-container":          "#4b8eff",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg:      "0.25rem",
                xl:      "0.5rem",
                full:    "0.75rem",
            },
            spacing: {
                "unit":             "8px",
                "gutter":           "24px",
                "margin-mobile":    "20px",
                "container-max":    "1200px",
                "stack-sm":         "8px",
                "margin-desktop":   "64px",
                "stack-md":         "24px",
                "stack-lg":         "48px",
            },
            fontFamily: {
                "display-lg-mobile": ["Inter"],
                "body-md":           ["Inter"],
                "display-lg":        ["Inter"],
                "label-mono":        ["JetBrains Mono"],
                "caption":           ["Inter"],
                "headline-sm":       ["Inter"],
                "headline-md":       ["Inter"],
                "body-lg":           ["Inter"],
            },
            fontSize: {
                "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "body-md":           ["16px", { lineHeight: "24px", fontWeight: "400" }],
                "display-lg":        ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
                "label-mono":        ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
                "caption":           ["12px", { lineHeight: "16px", fontWeight: "500" }],
                "headline-sm":       ["24px", { lineHeight: "32px", fontWeight: "600" }],
                "headline-md":       ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "body-lg":           ["18px", { lineHeight: "28px", fontWeight: "400" }],
            },
        },
    },
};
